appVersion: 0.1.0
description: A Helm chart for the Weave Scope cluster visualizer.
home: https://www.weave.works/oss/scope/
icon: https://avatars1.githubusercontent.com/u/9976052?s=64
keywords:
- containers
- dashboard
- monitoring
maintainers:
- email: github@orion-com.com
  name: omkensey
name: weave-scope-arm32v7
sources:
- https://github.com/weaveworks/scope
version: 0.10.0
