---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-pi-vol01-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
...
