- name: fetch common files
  become: yes
  fetch: dest={{ backup_dir }}/{{ inventory_hostname_short }}{{ item }} src={{ item }} flat=yes
  with_items:
  - /etc/hosts
  - /etc/hostname
  - /etc/network/interfaces
  - /var/lib/kubelet/config.yaml
  - /etc/dhcp/dhcpd.conf
  - /etc/dhcpcd.conf
  - /etc/wpa_supplicant/wpa_supplicant.conf
  - /etc/default/isc-dhcp-server
  - /etc/hostapd/hostapd.conf
  - /etc/iptables.ipv4.nat

- name: find interfaces files
  find:
    paths: /etc/network/interfaces.d/
  register: interface_files

- name: fetch interfaces files
  become: yes
  fetch: dest={{ backup_dir }}/{{ inventory_hostname_short }}{{ item.path }} src={{ item.path }} flat=yes
  with_items: "{{ interface_files.files }}"

- name: find kubernetes files
  find:
    paths: /etc/kubernetes/
    patterns: '*.conf,*.yaml'
    recurse: yes
  register: kubernetes_files

- name: fetch kubernetes files
  become: yes
  fetch: dest={{ backup_dir }}/{{ inventory_hostname_short }}{{ item.path }} src={{ item.path }} flat=yes
  with_items: "{{ kubernetes_files.files }}"

- name: find keys files
  find:
    paths: /etc/kubernetes/
    patterns: '*.crt,*.pub,*.key'
    recurse: yes
  register: kubernetes_keys

- name: create empty key
  become: yes
  fetch: dest={{ backup_dir }}/{{ inventory_hostname_short }}{{ item.path }} src=/dev/null flat=yes
  with_items: "{{ kubernetes_keys.files }}"

- name: find kubelet files
  find:
    paths: /etc/systemd/system/kubelet.service.d/
    patterns: '*.conf,*.yaml'
  register: kubelet_files

- name: fetch kubelet files
  become: yes
  fetch: dest={{ backup_dir }}/{{ inventory_hostname_short }}{{ item.path }} src={{ item.path }} flat=yes
  with_items: "{{ kubelet_files.files }}"


